### ISSUE TITLE
A keyfile was given, but it does not contain a project ID. This can indicate an old and obsolete keyfile, in which case you should create a new one. To suppress

### ISSUE THREAD

**Issue by zauradigozalov** [JoggApp/laravel-google-translate#1]
A keyfile was given, but it does not contain a project ID. This can indicate an old and obsolete keyfile, in which case you should create a new one. To suppress this message, set `suppressKeyFileNotice` to `true` in your client configuration. To learn more about generating new keys, see this URL: https://cloud.google.com/iam/docs/creating-managing-service-account-keys#creating_service_account_keys

**Comment by introwit** [comment]
@zauradigozalov why do we need to suppress the message when we want the user to create a new keyfile and the message helps convey that? 🙂

**Comment by girisuman98** [comment]
I'm also getting the same. Any help?

**Comment by LielZ** [comment]
there is an answer for that ?

**Comment by introwit** [comment]
This error only arises when you do not give it a config file. The steps to obtain the config file after applying the credit card (since this is a paid service by Google) are [detailed here](https://github.com/JoggApp/laravel-google-translate/blob/master/google.md) 🙂

**Comment by LielZ** [comment]
> This error only arises when you do not give it a config file. The steps to obtain the config file after applying the credit card (since this is a paid service by Google) are [detailed here](https://github.com/JoggApp/laravel-google-translate/blob/master/google.md) 🙂

oh, so its not really about the project id, its about the project doesn't activate.
thank you.
