### ISSUE TITLE
Exception when trying to call `GoogleTranslate::unlessLanguageIs('en',"hi this is test")`

### ISSUE THREAD

**Issue by shihabudheenf** [JoggApp/laravel-google-translate#10]
Non-static method JoggApp\GoogleTranslate\GoogleTranslate::unlessLanguageIs() should not be called statically

Using Laravel 6.

**Comment by introwit** [comment]
you need to import the facade provided by this pacakge at the top: `use GoogleTranslate;` and then use it in your code.

**Comment by shihabudheenf** [comment]
Thank you for reply, but now getting following error. 

![image](https://user-images.githubusercontent.com/2478715/70705714-865f0f80-1cfa-11ea-89d3-be6cdda3ca8a.png)

**Comment by shihabudheenf** [comment]
yes, it is working fine and thank you. .. but need subscirption :(
