### ISSUE TITLE
Doesn't work automatically register in Laravel 6.5.2

### ISSUE THREAD

**Issue by Khazhinov** [JoggApp/laravel-google-translate#11]
Hi!
After installation, the static methods call does not work.
To start, you need to call the GoogleTranslateClient constructor with the transfer of the configuration array, then the GoogleTranslate constructor. Further, the method call is available through the operator ->
I did a all cache cleanup. What could be the problem?

**Comment by introwit** [comment]
You don't need to call the client and pass anything. The facade does that for you automatically. Tried it on a fresh install as per the readme and it works perfectly.
