### ISSUE TITLE
passing dynamic language code to translate directive

### ISSUE THREAD

**Issue by Naveedali1234** [JoggApp/laravel-google-translate#13]
Greetings of the day. 

Thanks for this package. i am curious of how i can pass a dynamic language code to the translate directive. i tried the following:
`@translate('hello world',$country->locale)`

i am getting error on it.
`$country->locale` is the language code which i am fetching from database. your help would be really appreciated. 

thank you

**Comment by introwit** [comment]
It should work. Can you paste the exact error you are receiving?

**Comment by Naveedali1234** [comment]
![image](https://user-images.githubusercontent.com/17939653/76551123-0b51f480-64b5-11ea-81ff-f953251dee02.png)

here is the exact error by using the blade directive `@translate('Hello World',$country->locale)`.

**Comment by Naveedali1234** [comment]
am i using it wrong? your help would be really appreciated. when i put a static code like "fr" for french then it's working fine but when i add dynamic code then i am getting the above error.

**Comment by Naveedali1234** [comment]
can you help me out in it?

**Comment by Naveedali1234** [comment]
i am still stuck in it. what might be the issue?

**Comment by Naveedali1234** [comment]
still waiting :(

**Comment by introwit** [comment]
this might be a bug, will look into it once time allows. If you have any idea to fix the issue, feel free to send in a PR meanwhile.

**Comment by hfmiguel** [comment]
Hi , 
if you cant use the blade method , you can edit this file: 
vendor/joggapp/laravel-google-translate/src/GoogleTranslate.php

The method has a problem that this receive the language string with two ""  , we need to replace this "" .
On method: sanitizeLanguageCode()



Change to this.

public function sanitizeLanguageCode(string $languageCode)
    {
        $languageCode = trim(strtolower($languageCode));

        if ($languageCode === 'zh-tw') {
            $languageCode = 'zh-TW';
        }

        $languageCode = str_replace('"', '', $languageCode);

        if (in_array($languageCode, $this->languages())) {
            return $languageCode;
        }

        throw new Exception(
            "Invalid or unsupported ISO 639-1 language code -{$languageCode}-,
            get the list of valid and supported language codes by running GoogleTranslate::languages()"
        );
    }

**Comment by introwit** [comment]
@Naveedali1234 @hfmiguel thanks, I am looking into this today and will keep you posted

**Comment by introwit** [comment]
@Naveedali1234 @hfmiguel fixed in the new major release [v6.0.1](https://github.com/JoggApp/laravel-google-translate/releases/tag/v6.0.1)
