### ISSUE TITLE
Set source and target language code to prevent detection language call

### ISSUE THREAD

**Issue by lucaspontarolo** [JoggApp/laravel-google-translate#15]
It is possible to define a source and target language code? Because language detection generates costs.
Thanks!

**Comment by introwit** [comment]
a default target can already be set via the config file, please check the docs in readme. About the default source language, I will look into it, meanwhile feel free to send in a PR if you already have something in mind :)

**Comment by introwit** [comment]
will try to work on it for the next major release we have started to work on already. Will post updates here when available.
