### ISSUE TITLE
Update Version not working anymore

### ISSUE THREAD

**Issue by ChrisSantiago82** [JoggApp/laravel-google-translate#16]
Helllo,
This may not be an issue and probably I'm doing something wrong.
I'm trying to update from version 3.0 to the recent version.
Version 3.0 works like a charm, bur I need to update to a newer Laravel version and because of this I need to update this package.
Now I'm trying to make version 5 to work. 
On the landing page, you say how the config file looks like if you publish it.
And it says the parameter for the key is: 
**'key_file_path'** => base_path('composer.json'),
But if I publish the config file with the new version, it say **api_key** and not key_file_path
If I add the same value than before, of course it doesn't work anymore. But I'm guessing you don't want the path to the key anymore, you want the key itself? But I enter the key in the .env File, it doesn't work neither.
And of course, with the old version it works without any issue.
How can I set the key in this version?
I'm always getting this error:
![image](https://user-images.githubusercontent.com/43000085/80009049-8a642080-8496-11ea-89a7-f05bac1cacd6.png)

**Comment by ChrisSantiago82** [comment]
Maybe you can create me a new key?
https://github.com/JoggApp/laravel-google-translate/blob/master/google.md

**Comment by introwit** [comment]
sorry, the readme needs to be updated. You are correct the new version needs the api key itself. Steps on how to generate that from the google cloud console are documented here: https://github.com/JoggApp/laravel-google-translate/blob/master/google.md. I will update the readme to reflect the new changes, thank you 👍

**Comment by ChrisSantiago82** [comment]
Thank you for closing the issue. But sadly it still doesn't work. I have a valid key but doesn't matter how I do it, it won't work.

**Comment by introwit** [comment]
@ChrisSantiago82 it's not an issue with this package since the error clearly says that the key isn't valid. Maybe try a fresh install with all the steps mentioned in that file and try? It isn't an issue with the package code though

**Comment by ChrisSantiago82** [comment]
But I have the key working with the old version.

**Comment by ChrisSantiago82** [comment]
Why shouldn't it be possible to use that key?

**Comment by introwit** [comment]
@ChrisSantiago82 after upgrading the package, make the config file like the (new one)[https://github.com/JoggApp/laravel-google-translate/blob/master/config/googletranslate.php]. Then follow the steps (here)[https://github.com/JoggApp/laravel-google-translate/blob/master/google.md] to generate the key in the google console. Make sure that the env variable is same as the one referred in the config file. If the problem still persists saying the key is invalid, kindly contact the google cloud translate support forum: https://cloud.google.com/translate/docs/support

**Comment by ChrisSantiago82** [comment]
Have done it all of what you say and it doesn't work:
- Config file is the new one with the api_key and  env('GOOGLE_TRANSLATE_API_KEY').
- I have generated a new API key, and I have added it to the .env file (GOOGLE_TRANSLATE_API_KEY).
Still doesn't work and of course I have contacted the google support and they say everything is working. And that must be true because with the all version and the old key of course it's working.

**Comment by ChrisSantiago82** [comment]
Here is what I think the problem is:
In your example, you write that the key looks like this:
![image](https://user-images.githubusercontent.com/43000085/80083297-73b7db00-8523-11ea-892b-5eb0afc69c8c.png)
In the json file that is being generated and that has worked with the old version, there are two fields included private_key_id and private_key.
The key starts with -----BEGIN PRIVATE KEY----- and that is not how your example looks like.
But of course the private_key_id isn't working either. With the old version, if I just add that json file it works without any issues.

**Comment by introwit** [comment]
the last thing I can do is ask @michaviehauser to help you out as he worked on the upgrade. Micha can you shed some more light on the differences in types of key and what might be wrong in here?

**Comment by michaviehauser** [comment]
@ChrisSantiago82 please share your config file.

Also make sure the old config is not cached: php artisan cache:clear

**Comment by introwit** [comment]
@michaviehauser thank you for chipping in and helping ♥️ had a question for future reference: what exactly does the key look like in the new sdk version? Is it a small alpha numeric key or something like the older one starting with --Begin private key-- etc?

**Comment by ChrisSantiago82** [comment]
Hello michaviehauser.
I have cleared with php artisan cache:clear and it didn't help
That is how it looks like the googletranslate config file:
![image](https://user-images.githubusercontent.com/43000085/80119523-d034ed80-8557-11ea-9d41-fa6d6ff32442.png)

That is how the env file looks like:
![image](https://user-images.githubusercontent.com/43000085/80119679-04a8a980-8558-11ea-9440-47f2f7aa9486.png)

**Comment by ChrisSantiago82** [comment]
That is exactly my question as well. Do I have to enter the key, that is more than 2000 characters. Or the key Id?

**Comment by michaviehauser** [comment]
It is most likely an issue of using a wrong API key, or possibly Google Dashboard configuration.

The key is a short alpha-num similar to this example:
"AIzaSyAaSVb7pyRPm******************3wZg"

and can be obtained from the Google Cloud Platform following these instructions:
https://github.com/JoggApp/laravel-google-translate/blob/master/google.md

**Comment by introwit** [comment]
@michaviehauser thank you for your inputs Micha ♥️

**Comment by michaviehauser** [comment]
@introwit no worries, glad to help 👍

**Comment by ChrisSantiago82** [comment]
@michaviehauser 
@introwit
I wanted to thank you very much for your help. I could make it work. And you are correct, the problem was the key. My problem was that it's my clients google account and not mine and my client had to generate the key. And I'm guessing he did something wrong.
