### ISSUE TITLE
Can't translate to hebrew 'he'

### ISSUE THREAD

**Issue by LielZ** [JoggApp/laravel-google-translate#2]
'default_target_translation' => 'he' 
Throwing an error:

The default_target_translation value in the config/googletranslate.php file should be a valid lowercase ISO 639-1 code of the language.
I check in the list in google "https://cloud.google.com/translate/docs/languages" and its seems fine.

**Comment by LielZ** [comment]
Ok, just found it in "SupportedLanguages.php" file.
Thank you for a really great and simple translate !! 👍

**Comment by introwit** [comment]
@LielZ yep it was missing over there. Added it and tagged a [new release](https://github.com/JoggApp/laravel-google-translate/releases/tag/v1.0.1). You can run `composer update` in your project and you will have the new release with the fix. Thank you for pointing it out 🙂
