### ISSUE TITLE
Laravel 8

### ISSUE THREAD

**Issue by amrshawky35** [JoggApp/laravel-google-translate#20]
Can you please make a release for Laravel 8?

**Comment by introwit** [comment]
@amrshawky35 yes, will be doing that in a few hours for all our packages. Will notify here once done. Keeping the issue open until then.

**Comment by introwit** [comment]
@amrshawky35 a new major version has been [released and tagged](https://github.com/JoggApp/laravel-google-translate/releases/tag/v6.0.0) 👍

**Comment by amrshawky35** [comment]
Thank you :)
