### ISSUE TITLE
need to specific string translation for specific language code

### ISSUE THREAD

**Issue by techtic-hemant** [JoggApp/laravel-google-translate#25]
Laravel Version: ^7.0
joggapp/laravel-google-translate: ^6.0

We need to fix string translation for particular string for a specific language code and we are just use below function.

@translate('Testing string', $languageCode)

Appreciated in advance for your support!!!

**Comment by introwit** [comment]
the issue isn't exactly clear. To learn how to use the package, please refer the readme of the package thanks.
