### ISSUE TITLE
ErrorException Non-static method JoggApp\GoogleTranslate\GoogleTranslate::translate() should not be called statically

### ISSUE THREAD

**Issue by dagistan-tuncbilek** [JoggApp/laravel-google-translate#26]
I have tried everything that i found but not worked. GoogleTranslate is not facade.
Laravel 8 
PHP 7.4

**Comment by introwit** [comment]
import `use GoogleTranslate;` at the top of your file.

**Comment by dagistan-tuncbilek** [comment]
Thank for reply, but it doesnt work. I have tried all alternatives.

TypeError
Argument 1 passed to JoggApp\GoogleTranslate\GoogleTranslateClient::__construct() must be of the type array, null given, called in /Users/dagistantuncbilek/Documents/IT/Testing/laravel/vendor/joggapp/laravel-google-translate/src/GoogleTranslateServiceProvider.php on line 33

![Screenshot 2021-03-25 at 19 05 34](https://user-images.githubusercontent.com/58489760/112521808-38f69c80-8d9d-11eb-9e10-8e09ad8218a2.png)

**Comment by rafaelcalero** [comment]
Same problem here.

**Comment by gabrielesbaiz** [comment]
Try `\GoogleTranslate::...`
