### ISSUE TITLE
full configuration example in laravel

### ISSUE THREAD

**Issue by henry-ht** [JoggApp/laravel-google-translate#27]
I create this ticket because I did not find a solution to get the class to work.

Please can you create a written tutorial or setup video in laravel 7 or 8?

**Comment by henry-ht** [comment]
I apologize, I don't know but for some reason visual studio the extension of "php intellisense", it does not recognize it as a valid class and it always shows the error that the class is not defined

**Comment by lostincode** [comment]
Glad you got it sorted 👍
