### ISSUE TITLE
Default Source Language

### ISSUE THREAD

**Issue by ascanipek** [JoggApp/laravel-google-translate#28]
How to define default_target_translation? 

Google translate perceives some words differently than desired and the result is wrong

**Comment by lostincode** [comment]
Hey @ascanipek, if you take a peek at the readme file, you should find the answer. It's in the config file published by this package.

**Comment by ascanipek** [comment]
Hi again, I am sorry this is my mistake. Actually, I spelled it right in the title and wrong in the message. What I'm actually asking is is it possible for me to set the default source language?
