### ISSUE TITLE
Shared Hosting Problem

### ISSUE THREAD

**Issue by ascanipek** [JoggApp/laravel-google-translate#29]
I ran the package locally. But the project is running on shared hosting so I have to transfer it manually. First of all, I refreshed the vendor directory.

But when I try this code "use GoogleTranslate;" :
I get the error "Class 'GoogleTranslate' not found".

If "JoggApp\GoogleTranslate\GoogleTranslate" when I try this:
I get the error Non-static method JoggApp\GoogleTranslate\GoogleTranslate::justTranslate() should not be called statically.

It works locally without any problems, but if you have any advice on this, I would appreciate it.

I also manually imported the googletranslate.php config file into the config directory. And I added the api key to the env file.

**Comment by introwit** [comment]
we have never used it on shared hosting, so no idea about it.
