### ISSUE TITLE
How can I force the original language?

### ISSUE THREAD

**Issue by iec989** [JoggApp/laravel-google-translate#31]
I see in the instructions that I can send a second parameter with the destination language, but how do I ensure Google is picking the right original language? There are lots of false friends out there that could make Google be wrong when guessing the original language

Not sure if it would make sense to allow a third parameter here?
`GoogleTranslate::justTranslate($text,$lang);`

**Comment by introwit** [comment]
you can use the `detectLanguage` method for detecting the language first prior to translating it.

**Comment by iec989** [comment]
That doesn't answer the question though @introwit , this is not about detecting the language, but about saying which language Google should be transling from.

If I detect that the language is not the one I want, what should I do to force the original language?
