### ISSUE TITLE
Problem with UTF-8

### ISSUE THREAD

**Issue by josuelmm** [JoggApp/laravel-google-translate#33]
Hi. Have a problem with the translation
I use 
`$Translate = \GoogleTranslate::translate('Report interval in GPS auto mode, 10 - 60 minutes');`
I am translating into Spanish

Should return
`Intervalo de informe en modo automático GPS, 10 - 60 minutos`

And it's giving back
`Intervalo de informe en modo automu00e1tico GPS, 10 - 60 minutos`

That is to say
u00e1 = á

**Comment by mostafijartisan** [comment]
You can try this 'text' as third parameter like >> GoogleTranslate::translate($translationDataValues, $translation['to'],'text'); 


There is is an optional third parameter for format to take advantage for better html translation support. Google Translate API currently supports 'text' and 'html' as parameters. The default for this parameter is 'text' as it has the best use case for most translations. 
https://cloud.google.com/translate/docs/reference/rest/v2/translate

**Comment by introwit** [comment]
Mostafijur is right. Thanks :)
