### ISSUE TITLE
ReflectionException: Class "config" does not exist

### ISSUE THREAD

**Issue by introwit** [JoggApp/laravel-google-translate#39]
The tests are failing currently. Creating this issue to track this. Paging in @resslinger

**Comment by resslinger** [comment]
I have added a change with PR #40 

Can you start the checks for this PR?

**Comment by resslinger** [comment]
I think, we have to change the test case logic. I will start with them soon.

**Comment by introwit** [comment]
cool, thank you ❤️

**Comment by resslinger** [comment]
The tests are fixed. :)
