### ISSUE TITLE
Non static method 'detectLanguage' should not be called statically.

### ISSUE THREAD

**Issue by rafi-al-ahmad** [JoggApp/laravel-google-translate#44]
Hello, 
I'm trying to implement your package (V7.0) with my Laravel8 project but I'm facing this issue with calling methods **Non static method 'detectLanguage' should not be called statically.**

`use JoggApp\GoogleTranslate\GoogleTranslate;`

`

    public function index()
    {
        dd(GoogleTranslate::detectLanguage(['Hello world', 'Laravel is the best']));
    }

`

is there a problem with this implementation?

**Comment by introwit** [comment]
just do use GoogleTranslate;
