### ISSUE TITLE
Laravel 9 error on webserver

### ISSUE THREAD

**Issue by DevDJpl** [JoggApp/laravel-google-translate#46]
I have Laravel 9 and when I installed the package locally and then moved all files to my web server and created the Controller. When I gave use of GoogleTransleate; I have such an error Class "GoogleTranslate" not found. And I don't know what to do but I need it to run on my webserver. It is true that I reworked the function a bit because it is more convenient for me to use it and I did not want to play with overwriting the class function

![obraz](https://user-images.githubusercontent.com/29735167/180915879-883e9790-96e6-444b-8ce2-60461526b60b.png)

![obraz](https://user-images.githubusercontent.com/29735167/180916305-7579e422-599f-4bba-a3f7-d4f8c7481ac1.png)

![obraz](https://user-images.githubusercontent.com/29735167/180916469-89a29f3d-cebb-4ffc-8f5d-a62a17c419e7.png)

**Comment by introwit** [comment]
I tried the package in a fresh laravel v9 install and it works as expected. You might not have installed the package properly. Please refer to the package readme and follow all the steps.

**Comment by DevDJpl** [comment]
> I tried the package in a fresh laravel v9 install and it works as expected. You might not have installed the package properly. Please refer to the package readme and follow all the steps.

I did everything step by step as in the instructions and then chewed all the files on my webserver which I have on the hosting.

**Comment by DevDJpl** [comment]
I did everything step by step as in the instructions and then chewed all the files on my webserver which I have on the hosting.

**Comment by DevDJpl** [comment]
I did everything step by step as in the instructions and then chewed all the files on my webserver which I have on the hosting.

**Comment by DevDJpl** [comment]
I have heard from a few people that Laravel has such problems that packages do not always work as the developers would like them to and you have to register them manually. I also saw that not only I have such a problem because one person already had problems with hosting Laravel. I am able to provide access to my web server if necessary

**Comment by DevDJpl** [comment]
@introwit

**Comment by DevDJpl** [comment]
@introwit Okay, I solved the problem. I recommend you to change the GoogleTranslateServiceProvider file because it causes a problem and makes it not working on web hosting because when you manually register an alias and provider in the config / app.php file and change 2 lines in the GoogleTranslateServiceProvider file, it works normally.

From `__DIR__ . '/../config/googletranslate.php' => config_path('googletranslate.php'),`
To `config_path('googletranslate.php') => config_path('googletranslate.php'),`

From `$this->mergeConfigFrom(__DIR__ . '/../config/googletranslate.php', 'googletranslate');`
To `$this->mergeConfigFrom(config_path('googletranslate.php'), 'googletranslate');`
