### ISSUE TITLE
Spelling error in getAvailableTranslationsFor mismatch between readme.md and actual method

### ISSUE THREAD

**Issue by bmellink** [JoggApp/laravel-google-translate#48]
In the readme file it is spelled `getAvailableTranslationsFor`, but in the source code the function is called `getAvaliableTranslationsFor`.

Also the readme file indicates: "The translate method accepts a second optional argument which can be the code of the language you want the string to be translated in." This is not true: the second argument is the "from" language and the 3rd argument is the "to" language. An optional 4th parameter is the format.

**Comment by introwit** [comment]
@bmellink the typo is already fixed, although a release is pending. Can you send in a PR to fix the readme? I can cut a release after merging that one in.

**Comment by introwit** [comment]
tagged a new release. Also, Package is no longer actively developed, [more details here](https://github.com/JoggApp/laravel-google-translate/discussions/51)
