### ISSUE TITLE
Bad language pair: en|en

### ISSUE THREAD

**Issue by ComputerMaverick69** [JoggApp/laravel-google-translate#49]
Using the `unlessLanguageIs()` results in the above subject error. Per your documentation, `unlessLanguageIs()` should not translate if locale is same. Find below the code snippet throwing the error

```
<h2>{{ GoogleTranslate::unlessLanguageIs(app()->getLocale(), $headerFooter->footer_title) }}</h2>
<h3>{{ GoogleTranslate::unlessLanguageIs(app()->getLocale(), $headerFooter->footer_subtitle) }}</h3>
```

Not that the second parameter is data stored in 'en' in the database and should be translated to the user's locale considering the it's not same as the data.

**Comment by introwit** [comment]
Package is no longer actively developed, [more details here](https://github.com/JoggApp/laravel-google-translate/discussions/51)
