### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by yuri94** [JoggApp/laravel-google-translate#5]
Hi, when i try to install the package, laravel throw me this message:

`Using version ^2.0 for joggapp/laravel-google-translate
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install joggapp/laravel-google-translate v2.0.5
    - Conclusion: don't install joggapp/laravel-google-translate v2.0.4
    - Conclusion: don't install joggapp/laravel-google-translate v2.0.3
    - Conclusion: don't install joggapp/laravel-google-translate v2.0.2
    - Conclusion: don't install joggapp/laravel-google-translate v2.0.1
    - Conclusion: remove laravel/framework v5.4.36
    - Installation request for joggapp/laravel-google-translate ^2.0 -> satisfiable by joggapp/laravel-google-translate[v2.0.0, v2.0.1, v2.0.2, v2.0.3, v2.0.4, v2.0.5].
    - Conclusion: don't install laravel/framework v5.4.36
    - joggapp/laravel-google-translate v2.0.0 requires illuminate/support 5.8.* -> satisfiable by illuminate/support[v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.3, v5.8.4, v5.8.8, v5.8.9].
    - don't install illuminate/support v5.8.0|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.8.11|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.8.12|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.8.14|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.8.15|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.8.17|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.8.18|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.8.19|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.8.2|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.8.20|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.8.22|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.8.3|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.8.4|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.8.8|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.8.9|don't install laravel/framework v5.4.36
    - Installation request for laravel/framework (locked at v5.4.36, required as 5.4.*) -> satisfiable by laravel/framework[v5.4.36].

Installation failed, reverting ./composer.json to its original content.`

I think its because i use laravel 5.4 version. 
Have we any chance to downgrade the version to work with laravel 5.4?

**Comment by introwit** [comment]
nope, 5.8 is the minimum requirement. Sorry :slightly_smiling_face:
