### ISSUE TITLE
justTranslate from to issue

### ISSUE THREAD

**Issue by ChrisSantiago82** [JoggApp/laravel-google-translate#50]
I'm just updating from an older version to a new version.

The cool thing about justTranslate was that you only had to define the target language, and it works.
Now you either have to define the from and to language or it takes the config('googletranslate.default_source_translation').

My issue is, I don't know the source language, so it won't work just define it in the confic. Of course, I could first detect the language, and then use the justTranslate. But this is much more complicated then it was before: Because google translate will detect the source language itself.

This fix fixed the issue that there are 3 parameters required. But it destroyed the possibility to do without the language detection before. 
What do you think?
https://github.com/JoggApp/laravel-google-translate/commit/43550c61d75dc0b25fde447ef7833f2fd92c2f48
https://github.com/JoggApp/laravel-google-translate/commit/5803375b1e229867dbd128a55fe8b1e5b9006691

**Comment by introwit** [comment]
@ChrisSantiago82 happy new year! 🎉 We are open to merge in a new method which can be called something like `autoTranslate` or something similar which does what you specified. That way nothing breaks and we can tag a new minor release to ship that new method if you PR it :)

**Comment by introwit** [comment]
closing this issue. Package is no longer actively developed, [more details here](https://github.com/JoggApp/laravel-google-translate/discussions/51)
