### ISSUE TITLE
Class 'JoggApp\GoogleTranslate\GoogleTranslate' not found

### ISSUE THREAD

**Issue by hosamalzagh** [JoggApp/laravel-google-translate#6]
i run laravel 5.8 , in controller i write

use JoggApp\GoogleTranslate\GoogleTranslate;

GoogleTranslate::translate(['Hello world', 'Laravel is the best']);

i see
Class 'JoggApp\GoogleTranslate\GoogleTranslate' not found

**Comment by introwit** [comment]
You don't need to have that `use` statement since it's a facade. You can remove that `use JoggApp\GoogleTranslate\GoogleTranslate;` and the code should work 🙂

**Comment by hosamalzagh** [comment]
not work after remove 
use JoggApp\GoogleTranslate\GoogleTranslate;

**Comment by hosamalzagh** [comment]
i add manual     facade    'GoogleTranslate'=>JoggApp\GoogleTranslate\GoogleTranslate::class , in 
config/app
and still not work

**Comment by introwit** [comment]
ah sorry @hosamalzagh , you need to have `use GoogleTranslate ;`, then it should work :) lemme know

**Comment by lostincode** [comment]
@hosamalzagh try adding `use GoogleTranslate` at the top to utilize the Facade.

**Comment by hosamalzagh** [comment]
@introwit  @lostincode 
still not work

**Comment by introwit** [comment]
@hosamalzagh remove that line you added in config/app and run `composer dump-autoload -o` in your laravel project root

**Comment by hosamalzagh** [comment]
@introwit 
still not work

**Comment by hosamalzagh** [comment]
@introwit how to uninstall
